<html>
<body>
<div style="width: 100%;">
    <div style="width: 100%; text-align: center;">
        <div style="float: left; width: 20%; text-align: left;">
            <img src="assets/images/digital_bangladesh_logo.png" alt="" style="object-fit: contain;" />
        </div>
        <div style="float: left; width: 60%; text-align: center;">
            <h4>বাংলাদেশ টেলিযোগাযোগ নিয়ন্ত্রণ কমিশন</h4>
            <h4 style="font-size:14px">প্লট: ই-৫/এ, আগারগাঁও প্রশাসনিক এলাকা, শেরে-বাংলা নগর, ঢাকা-১২০৭।</h4>
            <h4 style="font-size:14px">www.btrc.gov.bd</h4>
        </div>
        <div style="float: left; width: 20%; text-align: right;">
            <img src="assets/images/new_images/logo.png" alt="" />
        </div>
    </div>
    <div style="width: 100%;  margin-top: 2%;">
        <div style="width: 50%; float: left; text-align: left;">
            <h5>স্মারক নম্বর: {{ $appInfo->sharok_no }}</h5>
        </div>
        <div style="width: 50%; float: left; text-align: right;">
            <h5>তারিখ: {{ \Carbon\Carbon::now()->format('d/m/Y') }}</h5>
        </div>
    </div>
    <div style="width: 100%;  text-align: left; margin-top: 2%;">
        বিষয়ঃ <b>তথ্য/ ডকুমেন্ট দাখিল প্রসঙ্গে।</b>
    </div>
    <div style="width: 100%; text-align: left; margin-top: 2%;">
        সূত্র: {{ $appInfo->tracking_no }}, তারিখ: {{\Carbon\Carbon::parse($appInfo->submitted_at)->format('d/m/Y')}} খ্রি:।
    </div>
    <div style="width: 100%; text-align: left; margin-top: 2%;">
        উপর্যুক্ত বিষয় ও সূত্রস্থ পত্রের প্রেক্ষিতে জানানো যাচ্ছে যে, আপনার প্রতিষ্ঠান  {{ $module_name }} সেবার জন্য কমিশন বরাবর আবেদন করলেও উক্ত আবেদনপত্রের সাথে নিম্নে বর্ণিত তথ্যাদি/ ডকুমেন্টস দাখিল করা হয়নি:
    </div>
    <div style="width: 100%; text-align: left; margin-top: 2%;">
       {!! $shortFallReason !!}
    </div>

    <div style="width: 100%; text-align: left; margin-top: 2%;">
        ০২। এমতাবস্তায়, উপরোক্ত তথ্যাদি সহ যথাযথ ভাবে পুনরায় অনলাইনে কমিশন বরাবর আবেদন করার জন্য নির্দেশক্রমে অনুরোধ জানানো হলো।
    </div>

    <div style="width: 100%; margin-top: 2%;  text-align: left;">
        <img src="data:image/png;base64,{{$qrCode}}" width="100px" height="100px" alt="barcode" />
    </div>
    <div style="width: 100%; text-align: left; margin-top: 2%;">
        {{ $ContactPersonData->designation }}<br>
       @if(!empty($companyInfo->org_nm)){{ $companyInfo->org_nm }}@endif<br>
        {{ $registerOfficeAddress }}, {{ $registerOfficeThana }}<br>
        {{ $registerOfficeDistrict }}

    </div>

    <div style="width: 100%; text-align: right; margin-top: 2%;">
        @if(!empty($signatory->signature_encode))
        <img style="text-align: right;" src="{{'data:image/jpeg;base64,'.$signatory->signature_encode}}" width="100px" alt="img"><br>
        <span>{{$signatory->user_first_name.''.$signatory->user_middle_name. '' .$signatory->user_last_name}}</span> <br>
        <span>{{$signatory->designation ?? ''}}</span> <br>
        <span>ফোন: {{$signatory->user_mobile ?? ''}}</span> <br>
        <span>ইমেইল: {{$signatory->user_email ?? ''}}</span> <br>
        @endif
    </div>
    <div style="width: 100%; text-align: left; margin-top: 2%;">
        সদয় অবগতি ও প্রয়োজনীয় কার্যার্থে প্রেরণ করা হলো ( জ্যেষ্ঠতার ক্রমানুসারে নয় ):
    </div>
    <div style="width: 100%; text-align: left; margin-top: 2%;">
        <ul style="list-style: none;">
            <li style="margin: 10px 0px 10px 0px">১ ) চেয়ারম্যান এর একান্ত সচিব, চেয়ারম্যান এর দপ্তর, বিটিআরসি ( মহোদয়ের সদয় অবগতির জন্য )।</li>
            <li style="margin: 10px 0px 10px 0px">২ ) অফিস কপি বিটিআরসি। &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Document Generated by https://lims.btrc.gov.bd
            </li>
        </ul>
    </div>

{{--    <div style="width: 100%; text-align: right; margin-top: 1%;">--}}
{{--        Document Generated by https://lims.btrc.gov.bd--}}
{{--    </div>--}}

</div>

</body>
</html>
